### ISSUE TITLE
Consider bellybutton

### ISSUE THREAD

**Issue by sobolevn** [dry-python/linters#23]
https://github.com/hchasestevens/bellybutton

Writing linters is hard. Writing `mypy` plugins is even harder.
I would suggest to bootstrap our development with declarative rule that can be defined as text.

Configuration example:
```yml
DeprecatedFnCall:
  description: `deprecated_fn` will be deprecated in v9.1.2. Please use `new_fn` instead.
  expr: //Call[func/Name/@id='deprecated_fn']
  example: "deprecated_fn(*values)"
  instead: "new_fn(values)"
```
